services:
    api:
        build:
            context: .
            target:  api-dev
        volumes:
            - .:/app
        ports:
            - 10001:80
        restart: unless-stopped
        depends_on:
            - database
        extra_hosts:
            - "host.docker.internal:host-gateway"

    database:
        image:   mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE:      case_study
            MYSQL_USER:          symfony
            MYSQL_PASSWORD:      symfony
        volumes:
            - mariadb_data:/var/lib/mysql:rw,delegated
        restart: no
        extra_hosts:
            - "host.docker.internal:host-gateway"

    pma:
        image:   phpmyadmin:5.1.3-apache
        restart: unless-stopped
        ports:
            # HTTP
            - 127.0.0.1:10010:80
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST:            database
            PMA_USER:            root
            PMA_PASSWORD:        root
            UPLOAD_LIMIT:        300M
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    mariadb_data:
